[build-system]
requires = ['setuptools>=42.0.0', 'wheel', 'setuptools_scm>=8.1']
build-backend = "setuptools.build_meta"

[project]
name = 'pinhole-effect'
version = '0.0.1'
description = 'This package simulates the pinhole effect in x-ray absorption spectroscopy due to thickness inhomogeneity and compares to the spectrum of a sample with uniform thickness.'
authors = [
  {name = 'Fiona McLary', email = 'fionaemw@uw.edu'}
  {name = 'Gerald T. Seidler', email = 'seidler@uw.edu'}
]
readme = 'README.md'
license = { file = 'LICENSE' }
requires-python = '>=3.10'
dependencies = [
  'numpy>=1.17',
  'scipy>=1.4',
  'matplotlib>=3.5',
  'pytest'

]
classifiers = [
  'Programming Language :: Python :: 3',
  'License :: OSI Approved :: MIT License',
  'Operating System :: OS Independent',
  'Intended Audience :: Science/Research',
  'Topic :: Scientific/Engineering :: Physics',
  'Topic :: Scientific/Engineering :: Chemistry'
]
